### ISSUE TITLE
No config found

### ISSUE THREAD

**Issue by ranaraheeltariq** [reliqarts/thujohn-twitter#3]
I'm follow all step that you mention in your documentation after that we can't found any ttwitter.php file in config folder.
`TWITTER_CONSUMER_KEY=
TWITTER_CONSUMER_SECRET=
TWITTER_ACCESS_TOKEN=
TWITTER_ACCESS_TOKEN_SECRET=`
i'm copy past in .env and inter my all keys but when i'm run function
`Route::get('/home', function(){
	Twitter::getSettings();
});`
found that error **No config found**

    public function __construct(Config $config, SessionStore $session){

        if ($config->has('ttwitter::config')) {

            $this->tconfig = $config->get('ttwitter::config');

        } elseif ($config->get('ttwitter')) {

            $this->tconfig = $config->get('ttwitter');

        } else {

            throw new RuntimeException('No config found');

        }`

**Comment by JayAhrDe** [comment]
Just to be sure: You did the publishing?
`php artisan vendor:publish --provider="ReliqArts\Thujohn\Twitter\TwitterServiceProvider"`

**Comment by reliq** [comment]
Hey @ranaraheeltariq,

If you published the config file as @JayAhrDe mentioned above and you are still experiencing this issue please provide the following information and I will look into this further:
- package version
- laravel version

Thanks

**Comment by reliq** [comment]
I'll close this since there has been no response for over a week.
