### ISSUE TITLE
Need to get headers while calling twitter endpoint

### ISSUE THREAD

**Issue by soju-ti** [reliqarts/thujohn-twitter#4]
Hi,
i would like to get the header information while calling twitter endpoint for instance                   
`$timeline = Twitter::getStatusesLookup($parameters)`
i can see those information in `Thujohn\Twitter\Twitter.php` in `public function query()` method.the response contain header information. but the function formats the response and only returns `response` key from the object.please support those header information in the response.Thanks in advance

**Comment by reliq** [comment]
Hi @soju-ti,

Respectfully closing this in favour of https://github.com/atymic/twitter/issues/306

Thank you
